name: LoveTweaks
version: '${project.version}'
main: me.lovelace.loveTweaks.LoveTweaks
api-version: '1.21'
softdepend:
  - PlaceholderAPI
  - Citizens
  - ItemsAdder

commands:
  lovetweaks:
    description: Команды администратора LoveTweaks
    usage: /lovetweaks <reload|givescroll|herald|post>
    permission: lovetweaks.admin
    permission-message: У вас нет прав для этой команды.
  scoreboard:
    description: Открыть настройки скорборда
    usage: /scoreboard
